//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionCitas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public Citas()
        {
            this.HistoriasClinicas = new HashSet<HistoriasClinicas>();
        }
    
        public int CitaID { get; set; }
        public int PacienteID { get; set; }
        public int PsicologoID { get; set; }
        public System.DateTime FechaHoraCita { get; set; }
        public string TipoCita { get; set; }
        public string Estado { get; set; }
        public string Notas { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
        public virtual Psicologos Psicologos { get; set; }
        public virtual ICollection<HistoriasClinicas> HistoriasClinicas { get; set; }
    }
}
